name: Go Package Release
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Go Tests
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.goversion }}
      - name: Setup Test Env
        run: docker-compose -f fixtures/docker-compose.yml up -d
      - name: Run tests
        run: go test -v  -covermode=count ./...
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}

  release:
    name: Go Package Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}