name: Go Package Release
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Go Message Client Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.goversion }}
      - name: Setup Test Env
        run: docker-compose -f fixtures/docker-compose.yml up -d
      - name: Run tests
        run: go test -v  -covermode=count ./...
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
    
  release:
    uses:  tommzn/github-ci/.github/workflows/go.pkg.release.yml@v1.0.60
    needs: [test]
    